const fs = require('fs');
const sc = fs.readFileSync('d:/Project/E-Nexus/frontend/src/components/StudentDashboard.jsx', 'utf8');
const bc = fs.readFileSync('d:/Project/E-Nexus/backend/controllers/studentController.js', 'utf8');
const ac = fs.readFileSync('d:/Project/E-Nexus/frontend/src/components/AdminDashboard.jsx', 'utf8');
console.log('=== STUDENT DASHBOARD ===');
console.log('attendanceSummary state:', sc.includes('attendanceSummary'));
console.log('percentage display:', sc.includes('attendanceSummary.percentage'));
console.log('5s polling:', sc.includes('fetchAttendanceSummary, 5000'));
console.log('Policy button:', sc.includes('Calculation Policy'));
console.log('Policy modal:', sc.includes('Bootcamp Attendance'));
console.log('=== BACKEND ===');
console.log('PRESENT filter:', bc.includes("status: 'PRESENT'"));
console.log('=== ADMIN DASHBOARD ===');
console.log('Overall % header:', ac.includes('Overall %'));
console.log('getOverallAttendance helper:', ac.includes('getOverallAttendance'));
console.log('uses full total (attendanceSessions.length):', ac.includes('attendanceSessions.length'));
console.log('Overall % cell in rows:', ac.includes('getOverallAttendance(student)'));
console.log('5s progress poll:', ac.includes('setInterval(() => fetchProgress'));
